# TODO Add SSL
# kibana behind reverse proxy
version: '3'
services:
  #setup
  setup:
    image: ubuntu:18.04
    container_name: setup
    volumes:
      - ${SETUP_LOCAL}:/mnt/setup/creds
    command:
      - bin/bash
      - -c
      - apt update && apt install apache2-utils -y && htpasswd -b -c /mnt/setup/creds/.credentials ${USER_NAME} ${PASSWORD}
    networks:
        esnet:
          ipv4_address: 172.19.0.7
  #nginx
  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - setup
      - es01
      - es02
      - es03
      - es04
      - es05
      - kb
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${SETUP_LOCAL}:/etc/nginx/creds/
    networks:
        esnet:
          ipv4_address: 172.19.0.2
# es pods
  es01:
    build:
      context: .
      dockerfile: elasticsearch-with-s3.Dockerfile
    container_name: elasticsearch1
    environment:
      - ES_JAVA_OPTS=${ALLOCATED_HEAP}
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${MEM_LIMIT}
    restart: always
    volumes:
      - ${DATA_LOCATION1}:/usr/share/elasticsearch/data
      - ./configs/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_LOG_LOCAL1}:/usr/share/elasticsearch/logs
      - ./configs/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
        esnet:
          ipv4_address: 172.19.0.3

  es02:
    build:
      context: .
      dockerfile: elasticsearch-with-s3.Dockerfile
    container_name: elasticsearch2
    environment:
      - ES_JAVA_OPTS=${ALLOCATED_HEAP}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${MEM_LIMIT}
    restart: always
    volumes:
      - ${DATA_LOCATION2}:/usr/share/elasticsearch/data
      - ./configs/es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_LOG_LOCAL2}:/usr/share/elasticsearch/logs
      - ./configs/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
        esnet:
          ipv4_address: 172.19.0.4

  es03:
    build:
      context: .
      dockerfile: elasticsearch-with-s3.Dockerfile
    container_name: elasticsearch3
    environment:
      - ES_JAVA_OPTS=${ALLOCATED_HEAP}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${MEM_LIMIT}
    restart: always
    volumes:
      - ${DATA_LOCATION3}:/usr/share/elasticsearch/data
      - ./configs/es03.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_LOG_LOCAL3}:/usr/share/elasticsearch/logs
      - ./configs/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
        esnet:
          ipv4_address: 172.19.0.5

  es04:
    build:
      context: .
      dockerfile: elasticsearch-with-s3.Dockerfile
    container_name: elasticsearch4
    environment:
      - ES_JAVA_OPTS=${ALLOCATED_HEAP}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${MEM_LIMIT}
    restart: always
    volumes:
      - ${DATA_LOCATION4}:/usr/share/elasticsearch/data
      - ./configs/es04.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_LOG_LOCAL4}:/usr/share/elasticsearch/logs
      - ./configs/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
        esnet:
          ipv4_address: 172.19.0.9
  es05:
    build:
      context: .
      dockerfile: elasticsearch-with-s3.Dockerfile
    container_name: elasticsearch5
    environment:
      - ES_JAVA_OPTS=${ALLOCATED_HEAP}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${MEM_LIMIT}
    restart: always
    volumes:
      - ${DATA_LOCATION5}:/usr/share/elasticsearch/data
      - ./configs/es05.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_LOG_LOCAL5}:/usr/share/elasticsearch/logs
      - ./configs/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
        esnet:
          ipv4_address: 172.19.0.10
#kibana
  kb:
    image: kibana:5.6.16
    container_name: kibana
    depends_on:
      - es01
      - es02
      - es03
      - es04
      - es05
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
    ports:
       - 127.0.0.1:5601:5601
    networks:
        esnet:
          ipv4_address: 172.19.0.6

  #monitor
  monitor:
    image: elastichq/elasticsearch-hq
    container_name: hq
    environment:
      HQ_DEFAULT_URL: 'http://es01:9200'
    depends_on:
      - es01
      - es02
      - es03
      - es04
      - es05
    ports:
       - 127.0.0.1:5000:5000
    networks:
        esnet:
          ipv4_address: 172.19.0.8

networks:
  esnet:
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
